/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class StoreManager extends javax.swing.JFrame {

    private JTextField getCbStreetOrCarCustomer;

    public StoreManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane15 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        pane = new javax.swing.JTabbedPane();
        customerPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCustomerCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCreateCustomer = new javax.swing.JButton();
        btnSearchCustomer = new javax.swing.JButton();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteCustomer = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtCustomerLastName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtdocumentCustomer = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnClearCustomer = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        scroll = new javax.swing.JScrollPane();
        tbCustomerInfo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtCustoAddressId = new javax.swing.JTextField();
        btnListCustomer = new javax.swing.JButton();
        pnAddress = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbStreetOrCarCustomer = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtNumberAdress = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCustomerCity = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNHoodCustomer = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtIdAddress = new javax.swing.JTextField();
        btnCreateAddress = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        btnSearchAddress = new javax.swing.JButton();
        btnUpdateAddress = new javax.swing.JButton();
        btnDeleteAddress = new javax.swing.JButton();
        btnClearAddress = new javax.swing.JButton();
        btnListAdress = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane12 = new javax.swing.JScrollPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        tbAddressInfo = new javax.swing.JTable();
        listPane = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtProductCode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnClearProducts = new javax.swing.JButton();
        txtNameProduct = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtCurrentPrice = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtStokeInStore = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtIdSuppliers = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtIdCategory = new javax.swing.JTextField();
        btnListProducts = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnCreateProduct = new javax.swing.JButton();
        btnSearchProduct = new javax.swing.JButton();
        btnUpdateProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbProductsInfo = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable5);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable6);

        jCheckBox1.setText("jCheckBox1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane15.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 650));
        setPreferredSize(new java.awt.Dimension(410, 500));

        pane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pane.setMinimumSize(new java.awt.Dimension(600, 320));
        pane.setPreferredSize(new java.awt.Dimension(600, 600));

        customerPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        customerPane.setMinimumSize(new java.awt.Dimension(430, 480));
        customerPane.setPreferredSize(new java.awt.Dimension(430, 480));

        jLabel1.setText("Code:");

        txtCustomerCode.setToolTipText("");

        jLabel2.setText(" Name: ");

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Information");

        btnCreateCustomer.setText("Create");
        btnCreateCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCreateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCustomerActionPerformed(evt);
            }
        });

        btnSearchCustomer.setText("Search");
        btnSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCustomerActionPerformed(evt);
            }
        });

        btnUpdateCustomer.setText("Update");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        btnDeleteCustomer.setText("Delete");
        btnDeleteCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustomerActionPerformed(evt);
            }
        });

        jLabel15.setText("Last Name: ");

        txtCustomerLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerLastNameActionPerformed(evt);
            }
        });

        jLabel16.setText("Idintification");

        txtdocumentCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdocumentCustomerActionPerformed(evt);
            }
        });

        btnClearCustomer.setText("Clear Fields");
        btnClearCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCustomerActionPerformed(evt);
            }
        });

        tbCustomerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id ", "Document", "Name", "Last Name", "Id_direccion"
            }
        ));
        scroll.setViewportView(tbCustomerInfo);

        jLabel5.setText("Id Address");

        btnListCustomer.setText("List All");
        btnListCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerPaneLayout = new javax.swing.GroupLayout(customerPane);
        customerPane.setLayout(customerPaneLayout);
        customerPaneLayout.setHorizontalGroup(
            customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPaneLayout.createSequentialGroup()
                .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPaneLayout.createSequentialGroup()
                        .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2))
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16))
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCustomerLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(txtCustomerName))
                                .addGap(36, 36, 36))
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdocumentCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(customerPaneLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCustomerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)))
                        .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addComponent(btnListCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231))
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addComponent(btnClearCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(customerPaneLayout.createSequentialGroup()
                        .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel3))
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtCustoAddressId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerPaneLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btnCreateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerPaneLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(customerPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10)
                            .addGroup(customerPaneLayout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        customerPaneLayout.setVerticalGroup(
            customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPaneLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel15))
                    .addGroup(customerPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClearCustomer))
                        .addGap(18, 18, 18)
                        .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtdocumentCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnListCustomer))
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCustoAddressId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pane.addTab("Customer", customerPane);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address:");

        cbStreetOrCarCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Street", "Career" }));

        jLabel18.setText("Number: ");

        jLabel19.setText("City:");

        jLabel20.setText("N/Hood");

        jLabel25.setText("ID address");

        txtIdAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAddressActionPerformed(evt);
            }
        });

        btnCreateAddress.setText("Create");
        btnCreateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAddressActionPerformed(evt);
            }
        });

        btnSearchAddress.setText("Search");

        btnUpdateAddress.setText("Update");

        btnDeleteAddress.setText("Delete");

        btnClearAddress.setText("Clear fields");

        btnListAdress.setText("List all");

        tbAddressInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Street", "Career", "Number", "N/hood", "City"
            }
        ));
        jScrollPane13.setViewportView(tbAddressInfo);

        jScrollPane12.setViewportView(jScrollPane13);

        javax.swing.GroupLayout pnAddressLayout = new javax.swing.GroupLayout(pnAddress);
        pnAddress.setLayout(pnAddressLayout);
        pnAddressLayout.setHorizontalGroup(
            pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddressLayout.createSequentialGroup()
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnAddressLayout.createSequentialGroup()
                        .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnAddressLayout.createSequentialGroup()
                                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnAddressLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25)
                                            .addGroup(pnAddressLayout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCustomerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cbStreetOrCarCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(pnAddressLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(btnClearAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnAddressLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(txtIdAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnAddressLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnAddressLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtNumberAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnAddressLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNHoodCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnAddressLayout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(btnListAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnAddressLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel4))
                            .addGroup(pnAddressLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnCreateAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnSearchAddress)
                                .addGap(20, 20, 20)
                                .addComponent(btnUpdateAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnDeleteAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(pnAddressLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnAddressLayout.setVerticalGroup(
            pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtIdAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbStreetOrCarCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumberAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(32, 32, 32)
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCustomerCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(txtNHoodCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19))
                .addGap(28, 28, 28)
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearAddress)
                    .addComponent(btnListAdress))
                .addGap(17, 17, 17)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAddress)
                    .addComponent(btnSearchAddress)
                    .addComponent(btnUpdateAddress)
                    .addComponent(btnDeleteAddress))
                .addGap(18, 18, 18))
        );

        pane.addTab("Addresses", pnAddress);

        jLabel17.setText("Product Code:");

        txtProductCode.setToolTipText("");

        jLabel6.setText("Product Name:");

        btnClearProducts.setText("Clear Fields");

        jLabel26.setText("Current Price:");

        txtCurrentPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurrentPriceActionPerformed(evt);
            }
        });

        jLabel27.setText("Stoke in Store");

        jLabel28.setText("Id Suppliers");

        jLabel29.setText("Id Categrory");

        btnListProducts.setText("List All");
        btnListProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListProductsActionPerformed(evt);
            }
        });

        btnCreateProduct.setText("Create");
        btnCreateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProductActionPerformed(evt);
            }
        });

        btnSearchProduct.setText("Search");

        btnUpdateProduct.setText("Update");

        btnDeleteProduct.setText("Delete");

        tbProductsInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "code", "Name", "Stoke in Store", "Id suppliers", "Id Category"
            }
        ));
        jScrollPane8.setViewportView(tbProductsInfo);

        jScrollPane14.setViewportView(jScrollPane8);

        javax.swing.GroupLayout listPaneLayout = new javax.swing.GroupLayout(listPane);
        listPane.setLayout(listPaneLayout);
        listPaneLayout.setHorizontalGroup(
            listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPaneLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnCreateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSearchProduct)
                .addGap(20, 20, 20)
                .addComponent(btnUpdateProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(listPaneLayout.createSequentialGroup()
                .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listPaneLayout.createSequentialGroup()
                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(listPaneLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(txtProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(listPaneLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(listPaneLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(listPaneLayout.createSequentialGroup()
                                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(listPaneLayout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel28))
                                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdSuppliers)
                                            .addGroup(listPaneLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtIdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(listPaneLayout.createSequentialGroup()
                                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStokeInStore, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(43, 43, 43)
                                .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnClearProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnListProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(listPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        listPaneLayout.setVerticalGroup(
            listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listPaneLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnClearProducts))
                    .addGroup(listPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStokeInStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))))
                .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)))
                    .addGroup(listPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnListProducts)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateProduct)
                    .addComponent(btnSearchProduct)
                    .addComponent(btnUpdateProduct)
                    .addComponent(btnDeleteProduct))
                .addGap(154, 154, 154))
        );

        pane.addTab("Products", listPane);

        jLabel12.setDisplayedMnemonic('S');
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Store Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateProductActionPerformed

    private void btnListProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListProductsActionPerformed

    private void txtCurrentPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurrentPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurrentPriceActionPerformed

    private void btnCreateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateAddressActionPerformed

    private void txtIdAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAddressActionPerformed

    private void btnListCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListCustomerActionPerformed

    private void btnClearCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearCustomerActionPerformed

    private void txtdocumentCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdocumentCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdocumentCustomerActionPerformed

    private void txtCustomerLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerLastNameActionPerformed

    private void btnDeleteCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustomerActionPerformed

    }//GEN-LAST:event_btnDeleteCustomerActionPerformed

    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed

    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCustomerActionPerformed

    }//GEN-LAST:event_btnSearchCustomerActionPerformed

    private void btnCreateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCustomerActionPerformed

    }//GEN-LAST:event_btnCreateCustomerActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed
   /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StoreManager().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearAddress;
    private javax.swing.JButton btnClearCustomer;
    private javax.swing.JButton btnClearProducts;
    private javax.swing.JButton btnCreateAddress;
    private javax.swing.JButton btnCreateCustomer;
    private javax.swing.JButton btnCreateProduct;
    private javax.swing.JButton btnDeleteAddress;
    private javax.swing.JButton btnDeleteCustomer;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnListAdress;
    private javax.swing.JButton btnListCustomer;
    private javax.swing.JButton btnListProducts;
    private javax.swing.JButton btnSearchAddress;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnUpdateAddress;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnUpdateProduct;
    private javax.swing.JComboBox<String> cbStreetOrCarCustomer;
    private javax.swing.JPanel customerPane;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JPanel listPane;
    private javax.swing.JTabbedPane pane;
    private javax.swing.JPanel pnAddress;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tbAddressInfo;
    private javax.swing.JTable tbCustomerInfo;
    private javax.swing.JTable tbProductsInfo;
    private javax.swing.JTextField txtCurrentPrice;
    private javax.swing.JTextField txtCustoAddressId;
    private javax.swing.JTextField txtCustomerCity;
    private javax.swing.JTextField txtCustomerCode;
    private javax.swing.JTextField txtCustomerLastName;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtIdAddress;
    private javax.swing.JTextField txtIdCategory;
    private javax.swing.JTextField txtIdSuppliers;
    private javax.swing.JTextField txtNHoodCustomer;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtNumberAdress;
    private javax.swing.JTextField txtProductCode;
    private javax.swing.JTextField txtStokeInStore;
    private javax.swing.JTextField txtdocumentCustomer;
    // End of variables declaration//GEN-END:variables

    public JTextField getGetCbStreetOrCarCustomer() {
        return getCbStreetOrCarCustomer;
    }

    public javax.swing.JButton getBtnClearCustomer() {
        return btnClearCustomer;
    }

    public javax.swing.JButton getBtnCreateCustomer() {
        return btnCreateCustomer;
    }
    
    public javax.swing.JButton getBtnDeleteCustomer() {
        return btnDeleteCustomer;
    }

    public javax.swing.JButton getBtnListCustomer() {
        return btnListCustomer;
    }

    public javax.swing.JButton getBtnSearchCustomer() {
        return btnSearchCustomer;
    }


    public javax.swing.JButton getBtnUpdateCustomer() {
        return btnUpdateCustomer;
    }

    public javax.swing.JComboBox<String> getCbStreetOrCarCustomer() {
        return cbStreetOrCarCustomer;
    }


    public javax.swing.JTable getTbCustomerInfo() {
        return tbCustomerInfo;
    }
    

    public javax.swing.JTextField getTxtCustoAddressId() {
        return txtCustoAddressId;
    }

    public javax.swing.JTextField getTxtCustomerCode() {
        return txtCustomerCode;
    }

    public javax.swing.JTextField getTxtCustomerLastName() {
        return txtCustomerLastName;
    }

    public javax.swing.JTextField getTxtCustomerName() {
        return txtCustomerName;
    }

    public javax.swing.JTextField getTxtIdAddress() {
        return txtIdAddress;
    }

    public javax.swing.JTextField getTxtNHoodCustomer() {
        return txtNHoodCustomer;
    }

    public javax.swing.JTextField getTxtNumberAdress() {
        return txtNumberAdress;
    }


    public javax.swing.JTextField getTxtdocumentCustomer() {
        return txtdocumentCustomer;
    }

    public javax.swing.JButton getBtnCreateAddress() {
        return btnCreateAddress;
    }

    public javax.swing.JButton getBtnCreateProduct() {
        return btnCreateProduct;
    }

    public javax.swing.JButton getBtnDeleteAddress() {
        return btnDeleteAddress;
    }

    public javax.swing.JButton getBtnDeleteProduct() {
        return btnDeleteProduct;
    }

    public javax.swing.JButton getBtnSearchAddress() {
        return btnSearchAddress;
    }

    public javax.swing.JButton getBtnSearchProduct() {
        return btnSearchProduct;
    }

    public javax.swing.JButton getBtnUpdateAddress() {
        return btnUpdateAddress;
    }

    public javax.swing.JButton getBtnUpdateProduct() {
        return btnUpdateProduct;
    }

    public javax.swing.JTable getTbAddressInfo() {
        return tbAddressInfo;
    }

    public javax.swing.JTextField getTxtCustomerCity() {
        return txtCustomerCity;
    }

    public javax.swing.JButton getBtnClearAddress() {
        return btnClearAddress;
    }

    public javax.swing.JButton getBtnListAddress() {
        return btnListAdress;
    }

    public javax.swing.JButton getBtnClearProducts() {
        return btnClearProducts;
    }

    public javax.swing.JTabbedPane getBtnCustomListAddress() {
        return pane;
    }

    public javax.swing.JButton getBtnListAdress() {
        return btnListAdress;
    }

    public javax.swing.JButton getBtnListProducts() {
        return btnListProducts;
    }

    public javax.swing.JTable getTbProductsInfo() {
        return tbProductsInfo;
    }

    public javax.swing.JTextField getTxtCurrentPrice() {
        return txtCurrentPrice;
    }

    public javax.swing.JTextField getTxtIdCategory() {
        return txtIdCategory;
    }

    public javax.swing.JTextField getTxtIdSuppliers() {
        return txtIdSuppliers;
    }

    public javax.swing.JTextField getTxtNameProduct() {
        return txtNameProduct;
    }

    public javax.swing.JTextField getTxtStokeInStore() {
        return txtStokeInStore;
    }

    public javax.swing.JTextField getTxtProductCode() {
        return txtProductCode;
    }
    
}
